name: user

on:
  push:
    paths:
      - 'cmd/user/*'
    branches:
      - main
  pull_request:
    paths:
      - 'cmd/user/*'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.55.2
          working-directory: cmd/user/

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Start test.
        run: go test -race -timeout=60s ./cmd/user/...
